export const countryCodes = [
    {
        name: "United States",
        code: "+1",
        length: 10,
        flag: "https://flagcdn.com/us.svg",
    },
    {
        name: "India",
        code: "+91",
        length: 10,
        flag: "https://flagcdn.com/in.svg",
    },
    {
        name: "United Kingdom",
        code: "+44",
        length: 10,
        flag: "https://flagcdn.com/gb.svg",
    },
    {
        name: "Germany",
        code: "+49",
        length: 11,
        flag: "https://flagcdn.com/de.svg",
    },
    {
        name: "France",
        code: "+33",
        length: 9,
        flag: "https://flagcdn.com/fr.svg",
    },
    {
        name: "Australia",
        code: "+61",
        length: 9,
        flag: "https://flagcdn.com/au.svg",
    },
    {
        name: "Sri Lanka",
        code: "+94",
        length: 9,
        flag: "https://flagcdn.com/lk.svg",
    },
    {
        name: "Pakistan",
        code: "+92",
        length: 10,
        flag: "https://flagcdn.com/pk.svg",
    },
    {
        name: "Bangladesh",
        code: "+880",
        length: 10,
        flag: "https://flagcdn.com/bd.svg",
    },
    {
        name: "Afghanistan",
        code: "+93",
        length: 9,
        flag: "https://flagcdn.com/af.svg",
    },
    {
        name: "China",
        code: "+86",
        length: 11,
        flag: "https://flagcdn.com/cn.svg",
    },
    {
        name: "New Zealand",
        code: "+64",
        length: 9,
        flag: "https://flagcdn.com/nz.svg",
    },
    {
        name: "Nepal",
        code: "+977",
        length: 10,
        flag: "https://flagcdn.com/np.svg",
    },
    {
        name: "Brazil",
        code: "+55",
        length: 11,
        flag: "https://flagcdn.com/br.svg",
    },
    {
        name: "Canada",
        code: "+1",
        length: 10,
        flag: "https://flagcdn.com/ca.svg",
    },
    {
        name: "Mexico",
        code: "+52",
        length: 10,
        flag: "https://flagcdn.com/mx.svg",
    },
    {
        name: "Russia",
        code: "+7",
        length: 10,
        flag: "https://flagcdn.com/ru.svg",
    },
    {
        name: "Japan",
        code: "+81",
        length: 10,
        flag: "https://flagcdn.com/jp.svg",
    },
    {
        name: "South Korea",
        code: "+82",
        length: 10,
        flag: "https://flagcdn.com/kr.svg",
    },
    {
        name: "South Africa",
        code: "+27",
        length: 9,
        flag: "https://flagcdn.com/za.svg",
    },
    {
        name: "Italy",
        code: "+39",
        length: 10,
        flag: "https://flagcdn.com/it.svg",
    },
    {
        name: "Spain",
        code: "+34",
        length: 9,
        flag: "https://flagcdn.com/es.svg",
    },
    {
        name: "Argentina",
        code: "+54",
        length: 10,
        flag: "https://flagcdn.com/ar.svg",
    },
    {
        name: "Turkey",
        code: "+90",
        length: 10,
        flag: "https://flagcdn.com/tr.svg",
    },
    {
        name: "Indonesia",
        code: "+62",
        length: 10,
        flag: "https://flagcdn.com/id.svg",
    },
    {
        name: "Vietnam",
        code: "+84",
        length: 10,
        flag: "https://flagcdn.com/vn.svg",
    },
    {
        name: "Malaysia",
        code: "+60",
        length: 10,
        flag: "https://flagcdn.com/my.svg",
    },
    {
        name: "Philippines",
        code: "+63",
        length: 10,
        flag: "https://flagcdn.com/ph.svg",
    },
    {
        name: "Thailand",
        code: "+66",
        length: 9,
        flag: "https://flagcdn.com/th.svg",
    },
    {
        name: "Saudi Arabia",
        code: "+966",
        length: 9,
        flag: "https://flagcdn.com/sa.svg",
    },
    {
        name: "United Arab Emirates",
        code: "+971",
        length: 9,
        flag: "https://flagcdn.com/ae.svg",
    },
    {
        name: "Iran",
        code: "+98",
        length: 10,
        flag: "https://flagcdn.com/ir.svg",
    },
    {
        name: "Egypt",
        code: "+20",
        length: 10,
        flag: "https://flagcdn.com/eg.svg",
    },
    {
        name: "Nigeria",
        code: "+234",
        length: 10,
        flag: "https://flagcdn.com/ng.svg",
    },
    {
        name: "Ethiopia",
        code: "+251",
        length: 9,
        flag: "https://flagcdn.com/et.svg",
    },
    {
        name: "Colombia",
        code: "+57",
        length: 10,
        flag: "https://flagcdn.com/co.svg",
    },
    {
        name: "Chile",
        code: "+56",
        length: 9,
        flag: "https://flagcdn.com/cl.svg",
    },
    {
        name: "Venezuela",
        code: "+58",
        length: 10,
        flag: "https://flagcdn.com/ve.svg",
    },
    {
        name: "Peru",
        code: "+51",
        length: 9,
        flag: "https://flagcdn.com/pe.svg",
    },
    {
        name: "Ukraine",
        code: "+380",
        length: 9,
        flag: "https://flagcdn.com/ua.svg",
    },
    {
        name: "Poland",
        code: "+48",
        length: 9,
        flag: "https://flagcdn.com/pl.svg",
    },
    {
        name: "Netherlands",
        code: "+31",
        length: 9,
        flag: "https://flagcdn.com/nl.svg",
    },
    {
        name: "Belgium",
        code: "+32",
        length: 9,
        flag: "https://flagcdn.com/be.svg",
    },
    {
        name: "Sweden",
        code: "+46",
        length: 9,
        flag: "https://flagcdn.com/se.svg",
    },
    {
        name: "Switzerland",
        code: "+41",
        length: 9,
        flag: "https://flagcdn.com/ch.svg",
    },
    {
        name: "Austria",
        code: "+43",
        length: 10,
        flag: "https://flagcdn.com/at.svg",
    },
    {
        name: "Greece",
        code: "+30",
        length: 10,
        flag: "https://flagcdn.com/gr.svg",
    },
    {
        name: "Portugal",
        code: "+351",
        length: 9,
        flag: "https://flagcdn.com/pt.svg",
    },
    {
        name: "Czech Republic",
        code: "+420",
        length: 9,
        flag: "https://flagcdn.com/cz.svg",
    },
    {
        name: "Hungary",
        code: "+36",
        length: 9,
        flag: "https://flagcdn.com/hu.svg",
    },
    {
        name: "Romania",
        code: "+40",
        length: 10,
        flag: "https://flagcdn.com/ro.svg",
    },
    {
        name: "Finland",
        code: "+358",
        length: 9,
        flag: "https://flagcdn.com/fi.svg",
    },
    {
        name: "Denmark",
        code: "+45",
        length: 8,
        flag: "https://flagcdn.com/dk.svg",
    },
    {
        name: "Norway",
        code: "+47",
        length: 8,
        flag: "https://flagcdn.com/no.svg",
    },
    {
        name: "Ireland",
        code: "+353",
        length: 9,
        flag: "https://flagcdn.com/ie.svg",
    },
    {
        name: "Slovakia",
        code: "+421",
        length: 9,
        flag: "https://flagcdn.com/sk.svg",
    },
    {
        name: "Slovenia",
        code: "+386",
        length: 9,
        flag: "https://flagcdn.com/si.svg",
    },
    {
        name: "Croatia",
        code: "+385",
        length: 9,
        flag: "https://flagcdn.com/hr.svg",
    },
    {
        name: "Serbia",
        code: "+381",
        length: 9,
        flag: "https://flagcdn.com/rs.svg",
    },
    {
        name: "Bulgaria",
        code: "+359",
        length: 9,
        flag: "https://flagcdn.com/bg.svg",
    },
];
