export const dateFormats = [
    "YYYY-MM-DD",
    "DD-MM-YYYY",
    "MM-DD-YYYY",
    "YYYY/MM/DD",
    "DD/MM/YYYY",
    "MM/DD/YYYY",
    "YYYY.MM.DD",
    "DD.MM.YYYY",
    "MM.DD.YYYY",
    "dddd, MMMM D, YYYY", 
    "MMM D, YYYY",
    "D MMM YYYY", 
    "D MMMM YYYY", 
];

export const timeFormats = [
    "12 Hour (AM/PM)",
    "24 Hour",
    "hh:mm A", 
    "HH:mm", 
    "hh:mm:ss A",
    "HH:mm:ss", 
];

export const timezones = [
    "UTC",
    "GMT",
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Toronto",
    "America/Vancouver",
    "Europe/London",
    "Europe/Paris",
    "Europe/Berlin",
    "Europe/Rome",
    "Europe/Madrid",
    "Europe/Amsterdam",
    "Europe/Athens",
    "Asia/Kolkata",
    "Asia/Tokyo",
    "Asia/Shanghai",
    "Asia/Dubai",
    "Asia/Hong_Kong",
    "Asia/Singapore",
    "Asia/Seoul",
    "Asia/Bangkok",
    "Australia/Sydney",
    "Australia/Melbourne",
    "Australia/Brisbane",
    "Pacific/Honolulu",
    "Pacific/Fiji",
    "Africa/Johannesburg",
    "Africa/Lagos",
    "Africa/Cairo",
    "South America/Sao_Paulo",
];

export const currencies = [
    { label: "USD ($)", value: "USD" },
    { label: "INR (₹)", value: "INR" },
    { label: "EUR (€)", value: "EUR" },
    { label: "GBP (£)", value: "GBP" },
    { label: "JPY (¥)", value: "JPY" },
    { label: "AUD (A$)", value: "AUD" },
    { label: "CAD (C$)", value: "CAD" },
    { label: "SGD (S$)", value: "SGD" },
    { label: "CHF (CHF)", value: "CHF" },
    { label: "CNY (¥)", value: "CNY" },
    { label: "HKD (HK$)", value: "HKD" },
    { label: "NZD (NZ$)", value: "NZD" },
    { label: "KRW (₩)", value: "KRW" },
    { label: "BRL (R$)", value: "BRL" },
    { label: "ZAR (R)", value: "ZAR" },
    { label: "THB (฿)", value: "THB" },
    { label: "AED (د.إ)", value: "AED" },
    { label: "SAR (﷼)", value: "SAR" },
    { label: "RUB (₽)", value: "RUB" },
    { label: "MXN ($)", value: "MXN" },
    { label: "PHP (₱)", value: "PHP" },
    { label: "IDR (Rp)", value: "IDR" },
    { label: "TRY (₺)", value: "TRY" },
    { label: "PLN (zł)", value: "PLN" },
    { label: "NOK (kr)", value: "NOK" },
    { label: "SEK (kr)", value: "SEK" },
    { label: "DKK (kr)", value: "DKK" },
    { label: "HUF (Ft)", value: "HUF" },
];

export const sessionDrivers = ["File", "Database", "Redis", "Memcached"];

export const rowLimits = ["10", "25", "50", "100", "200", "500"];

export const languages = [
    "English",
    "Spanish",
    "French",
    "German",
    "Hindi",
    "Mandarin Chinese",
    "Portuguese",
    "Russian",
    "Japanese",
    "Korean",
    "Arabic",
    "Bengali",
    "Turkish",
    "Italian",
    "Vietnamese",
    "Thai",
    "Polish",
    "Dutch",
    "Filipino",
    "Swedish",
    "Greek",
    "Hebrew",
    "Indonesian",
    "Malay",
    "Czech",
    "Hungarian",
    "Danish",
    "Finnish",
    "Norwegian",
    "Ukrainian",
    "Romanian",
];
